# Generated by Django 2.2.2 on 2019-06-20 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_add', models.DateField(auto_now_add=True)),
                ('desciption', models.TextField(null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_add', models.DateTimeField(auto_now_add=True)),
                ('account_data', models.DateField(verbose_name='Data')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Valor')),
                ('type', models.CharField(choices=[('receber', 'receber'), ('pagar', 'pagar')], max_length=14, verbose_name='Tipo')),
                ('type_payment', models.CharField(choices=[('dinheiro', 'dinheiro'), ('cartão', 'cartão'), ('transferência', 'transferência')], max_length=8, verbose_name='Meio de pagamento')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categories', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
    ]
